// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0D7_t1wO968JLg8yohHs7Y23_Vvzcswg',
    appId: '1:334784489827:web:fea609db20cb4b05268b56',
    messagingSenderId: '334784489827',
    projectId: 'namaa-62800',
    authDomain: 'namaa-62800.firebaseapp.com',
    storageBucket: 'namaa-62800.firebasestorage.app',
    measurementId: 'G-WP6YV1BE9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5cwK-TXWkPrquWbpbAN3vd0A4hQyBio',
    appId: '1:334784489827:android:ae1dc6e3441a5dad268b56',
    messagingSenderId: '334784489827',
    projectId: 'namaa-62800',
    storageBucket: 'namaa-62800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy0GutESC6jaqyDLTZXjuZhK10OSOS7PM',
    appId: '1:334784489827:ios:de6fd90e0f45fb54268b56',
    messagingSenderId: '334784489827',
    projectId: 'namaa-62800',
    storageBucket: 'namaa-62800.firebasestorage.app',
    iosBundleId: 'com.example.namaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy0GutESC6jaqyDLTZXjuZhK10OSOS7PM',
    appId: '1:334784489827:ios:de6fd90e0f45fb54268b56',
    messagingSenderId: '334784489827',
    projectId: 'namaa-62800',
    storageBucket: 'namaa-62800.firebasestorage.app',
    iosBundleId: 'com.example.namaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0D7_t1wO968JLg8yohHs7Y23_Vvzcswg',
    appId: '1:334784489827:web:a7a7cc62074bc037268b56',
    messagingSenderId: '334784489827',
    projectId: 'namaa-62800',
    authDomain: 'namaa-62800.firebaseapp.com',
    storageBucket: 'namaa-62800.firebasestorage.app',
    measurementId: 'G-H4CK8316Q0',
  );
}
